



development:
  adapter: postgresql
  encoding: unicode
  database: ajaxtable
  pool: 5
  username: shaitan
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: ajaxtable3
  pool: 5
  username: shaitan
  password: 123456










